### ISSUE TITLE
"Using Pilot Systems...." paper entry is wrong

### ISSUE THREAD

**Issue by iparask** [radical-group/radical-group.github.io#100]
The link name is not according the format described in the README file. Furthermore the paper link points to a PDF file and not the actual publication page.

@andre-merzky, can you please fix this? Thank you

**Comment by andre-merzky** [comment]
Sure, happy to do.  I don't think though there exists a specific publication pages from JSSP for that paper - thus the link to the PDF.  Any suggestion?

I am also not exactly sure what 'link name' you refer to... :(

**Comment by mturilli** [comment]
Here the landing page:

https://www.springer.com/us/book/9783030106317

And the full bibtex entry. @iparask I would like to review the idea of NOT adding the bib entry. After spending a good 3 hours today for the Nth time to remake some of our bib entries I am acutely aware of how helpful it would be to have them right away on our website.

```
@inproceedings{merzky2018using,
  title={Using Pilot Systems to Execute Many Task Workloads on Supercomputers},
  author={Merzky, Andre and Turilli, Matteo and Maldonado, Manuel and Santcroos, Mark and Jha, Shantenu},
  editor={Klus{\'a}{\v{c}}ek, Dalibor and Cirne, Walfredo and Desai, Narayan},
  booktitle={Job Scheduling Strategies for Parallel Processing: 22nd International Workshop, JSSPP 2018, Vancouver, BC, Canada, May 25, 2018, Revised Selected Paper},
  year={2019},
  pages={61--82},
  organization={Springer},
}
```
