### ISSUE TITLE
Update for documentation

### ISSUE THREAD

**Issue by aydinsaribudak** [radical-group/radical-group.github.io#116]
Missing commands for local run instructions:
"sudo gem install pygments.rb"
"sudo gem install bundler"
"bundle install"
Clone repository before and run "jekyll serve" under the repository folder

**Comment by iparask** [comment]
I updated the README file. `pygments.rb` is a ruby for syntax highlighting, and as a result it is not necessary. `sudo gem install bundler` was already part of the instructions. I also added the sentence to clone the repo before running `jekyll serve`
