### ISSUE TITLE
Project page

### ISSUE THREAD

**Issue by mturilli** [radical-group/radical-group.github.io#14]
I would suggest to group radical-pilot and entk under the RCT project.

**Comment by iparask** [comment]
Then doesn't almost everything go under the RCT project? Unless EnTK as a research project gets merged with SAGA and RP

**Comment by shantenujha** [comment]
I would echo that "radical-pilot and entk" go under RCT. EnTK is under RCT but not the EarthCube project "harnessing the power of many"... Make sense?

**Comment by mturilli** [comment]
Done. See #27
