### ISSUE TITLE
Adding publications

### ISSUE THREAD

**Issue by mturilli** [radical-group/radical-group.github.io#30]
Every first author to add their publications. Please add missing entries to the following list.

Andre:
- [x] A. Merzky, M. T. Ha, M.Turilli, S. Jha. “Synapse: Synthetic application profiler and em-ulator”, Journal of Computational Science, vol. 27, pp. 329–344.
- [x] A. Merzky, M. Turilli, M. Maldonado, M. Santcroos, S. Jha. “Using Pilot Systems to Execute Many Task Workloads on Supercomputers”. Accepted in LNCS proceedings of the 22nd Workshop on Job Scheduling Strategies for Parallel Processing (JSSPP).

Jumana:
- [x] J. Dakka, K. Farkas-Pall, V. Balasubramanian, M. Turilli, S. Wan, D. W. Wright, S. Za-sada, P. V. Coveney, S. Jha, “Rapid, concurrent and adaptive extreme scale binding free energy calculation”. Accepted in Proceedings of the 18th IEEE/ACM International Symposium on Cluster, Cloud and Grid Computing (CCGrid).
- [x] J. Dakka, K. Farkas-Pall, M. Turilli, D. W. Wright, P. V. Coveney, S. Jha. “Concurrent and Adaptive Extreme Scale Binding Free Energy Calculations”. Accepted in Proceed-ings of the 14th IEEE International Conference on e-Science.

Matteo:
- [x] M. Turilli, A. Merzky, V. Balasubramanian, S. Jha. “Building Blocks for Workflow Sys-tem Middleware”. Accepted in Proceedings of the 18th IEEE/ACM International Sym-posium on Cluster, Cloud and Grid Computing (CCGrid), 2018.

**Comment by jdakka** [comment]
see [pull request](https://github.com/radical-group/radical-group.github.io/pull/55)

**Comment by mturilli** [comment]
@shantenujha What is the author list/order in the paper of the scale challenge (CCGrid)? In the review email you forward I see: "Shantenu Jha, Jumana Dakka, David Wright and Matteo Turilli". If that is indeed the correct list, could you add your publication?

**Comment by jdakka** [comment]
The link to the paper: http://ccs.chem.ucl.ac.uk/sites/ccs.chem.ucl.ac.uk/files/scale2018-ccgrid_0.pdf

**Comment by shantenujha** [comment]
https://ieeexplore.ieee.org/document/8411074

**Comment by mturilli** [comment]
@jdakka thanks. Would you mind to add that to publications too (with a note about winning the SCALE challenge)?

**Comment by iparask** [comment]
I think this can close, right?

**Comment by mturilli** [comment]
Done!
