### ISSUE TITLE
Reduce text in project landing pages to a single paragraph

### ISSUE THREAD

**Issue by mturilli** [radical-group/radical-group.github.io#32]
Giannis:
- [x]  MIDAS

Jumana:
- [x]  HTBAC

Matteo:
- [x] CCC
- [x]  ExTASY
- [x]  ICEBERG
- [x] The Power of Many

**Comment by jdakka** [comment]
Pull request: https://github.com/radical-group/radical-group.github.io/pull/35

**Comment by mturilli** [comment]
See #41, #40, #39, #38

**Comment by iparask** [comment]
See PR #44

**Comment by mturilli** [comment]
All the listed projects have been reduced
