### ISSUE TITLE
Stale RCT Twitter account

### ISSUE THREAD

**Issue by mturilli** [radical-group/radical-group.github.io#51]
Last post on 17 May 2017. Should we close it?

**Comment by mturilli** [comment]
Keep if automatic posting from https://github.com/radical-cybertools/radical.pilot/issues/1772 is implemented

**Comment by shantenujha** [comment]
I'm fine with closing RCT if there isn't a plan to continue to use it.

**Comment by iparask** [comment]
Someone should close the other account and point those following there to the new one. I will ask Aymen if he can create a logo for the whole lab.

**Comment by mturilli** [comment]
@iparask: do we have a logo? I send an email to Iain, let's see whether he still have the login info about the stake account.

**Comment by iparask** [comment]
No, we do not. I think Aymen would create one. I will ask him again in case he has done something.

**Comment by mturilli** [comment]
The RCT twitter account is now closed.

**Comment by iparask** [comment]
So we can close this one right?
