### ISSUE TITLE
Create a RADICAL Lab twitter account

### ISSUE THREAD

**Issue by mturilli** [radical-group/radical-group.github.io#54]
How do we call it?

**Comment by shantenujha** [comment]
radical-lab? if that is taken, then radical-research? if that is also taken, then radical-team ?

**Comment by mturilli** [comment]
Dash is not allowed but we can use underscore. 

The following are taken:
- RadicalLab
- RadicalResearch 
- RadicalTeam
- Radical_Team
- TeamRadical

This is too long:
- Radical_Research

We could have:
- Radical_Lab
- LabRadical

Preferences?

**Comment by shantenujha** [comment]
LabRadical is fine (as long as it isn't: Le laboratoire RADICAL :) )

**Comment by mturilli** [comment]
Done: https://twitter.com/LabRadical

**Comment by shantenujha** [comment]
And don't forget to link it to the "News" which currently still points to https://twitter.com/RCT_Rutgers

**Comment by iparask** [comment]
Pull Request #91 takes care of all these issues.
