### ISSUE TITLE
Personal figure

### ISSUE THREAD

**Issue by iparask** [radical-group/radical-group.github.io#6]
Please add your picture and update personal webpage

**Comment by iparask** [comment]
ping @andre-merzky

**Comment by andre-merzky** [comment]
Seems I need to take a picture of myself then - will do :-)

**Comment by mturilli** [comment]
We can get one next week when you are here :)

**Comment by iparask** [comment]
That is true!

**Comment by shantenujha** [comment]
@andre-merzky  -- I still see the picture at http://radical.rutgers.edu/people/andre_merzky being closer to Darth Vader..

**Comment by iparask** [comment]
This will be fixed as soon as PR #22 is approved. Still review pending from @shantenujha and @vivek-bala

**Comment by mturilli** [comment]
@shantenujha, @vivek-bala: please review and approve/comment on #22
