### ISSUE TITLE
Travis is sensitive to external URLs time responses

### ISSUE THREAD

**Issue by iparask** [radical-group/radical-group.github.io#79]
Travis builds are sensitive to external URLs response time. I will try to increase the time it takes before it times out so that we reduce the probability of it failing because some other server is slow.

**Comment by mturilli** [comment]
It seems that many sites black list Travis like, for example, those that I white-listed in `/script/cibuild`. Let's see whether a longer time out helps to discriminate between black-listing and 'it takes just a while' :)

**Comment by mturilli** [comment]
So far so good. I am going to close this and reopen in case the issue shows up again.
