### ISSUE TITLE
People's page on a phone

### ISSUE THREAD

**Issue by iparask** [radical-group/radical-group.github.io#95]
I tried to see the people's page from my phone and it keep the three column setup. Here is a picture of that:

![image](https://user-images.githubusercontent.com/8268665/50348095-cafc0480-0505-11e9-814a-3289968bbcdb.png)

I will try to see how to make this part responsive to screens that cannot keep the three column setup.

**Comment by mturilli** [comment]
Apologies, I did that page before studying the responsive functionalities in SCSS. Let me fix that

**Comment by iparask** [comment]
I am still not sure how to do this. If you think it is quick feel free to fix it.
