### ISSUE TITLE
Link does not exist any more

### ISSUE THREAD

**Issue by iparask** [radical-group/radical-group.github.io#99]
Hello,

a link from eScience2009 point to Microsoft Research is not working any more. It is:
http://research.microsoft.com/en-us/UM/redmond/events/eScience2009/17863/lecture.htm

I will try and find from it comes from (most probably a publication), but if you have an idea, fell free to fix it.

**Comment by mturilli** [comment]
At he moment, I see 8 failing links but all related to OGF:

https://travis-ci.org/radical-group/radical-group.github.io

The OGF site seems down. I would wait a bit and see whether the website comes back up.

**Comment by andre-merzky** [comment]
OGF's server has a disk error.  Backup is being played back, but it might take a while (IU support is not the quickest).

**Comment by iparask** [comment]
That is correct. The MS link does not fail, because MS redirects it. But if you follow it, you will see that it does not go to the intended content.

I do not mind, but it is outdated.

**Comment by mturilli** [comment]
@iparask can you post here the link(s) of the page of our website that contain that MS link?
